//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeGlutenApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FreeGlutenEntities : DbContext
    {
        public FreeGlutenEntities()
            : base("name=FreeGlutenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lugares> Lugares { get; set; }
        public virtual DbSet<Menus> Menus { get; set; }
        public virtual DbSet<NivelCeliaquismo> NivelCeliaquismo { get; set; }
        public virtual DbSet<Recetas> Recetas { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
