//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeGlutenApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menus()
        {
            this.Lugares = new HashSet<Lugares>();
        }
    
        public string NombreMenu { get; set; }
        public Nullable<double> Precio { get; set; }
        public int id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> id_Nivel { get; set; }
    
        public virtual NivelCeliaquismo NivelCeliaquismo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lugares> Lugares { get; set; }
    }
}
